package 第4到27章_23大设计模式.第13章_享元模式.部门经理作汇报的例子;

import org.junit.Test;

public class EmployeeFactoryTest {
    private static final String[] departments = {"RD", "QA", "PM", "BD"};

    @Test
    public void test() {
        for (int i = 0; i < 10; i++) {
            // 随机取一个部门
            String department = departments[(int) (Math.random() * departments.length)];
            Manager manager = (Manager) EmployeeFactory.getManager(department);
            manager.report();
        }
    }
    /**
     * 创建部门经理：PM 创建报告：PM部门汇报：此次报告的主要内容是......
     * PM部门汇报：此次报告的主要内容是......
     * PM部门汇报：此次报告的主要内容是......
     * 创建部门经理：QA 创建报告：QA部门汇报：此次报告的主要内容是......
     * QA部门汇报：此次报告的主要内容是......
     * PM部门汇报：此次报告的主要内容是......
     * QA部门汇报：此次报告的主要内容是......
     * 创建部门经理：BD 创建报告：BD部门汇报：此次报告的主要内容是......
     * BD部门汇报：此次报告的主要内容是......
     * PM部门汇报：此次报告的主要内容是......
     * PM部门汇报：此次报告的主要内容是......
     * 创建部门经理：RD 创建报告：RD部门汇报：此次报告的主要内容是......
     * RD部门汇报：此次报告的主要内容是......
     * BD部门汇报：此次报告的主要内容是......
     */
}